import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { finalize } from 'rxjs';
import { AuthService } from '../../../../core/services/auth.service';
import { ComplianceCertificate, ReportOwnerOption, ReportsService } from '../../../../core/services/reports.service';
import { OwnerPickerComponent } from '../../shared/owner-picker/owner-picker';

/**
 * A compliance statement for one document owner, from their latest compliance check.
 * It is only a certificate of compliance when the owner is fully compliant; otherwise it says what is outstanding.
 */
@Component({
  selector: 'app-compliance-certificate',
  standalone: true,
  imports: [CommonModule, OwnerPickerComponent],
  templateUrl: './compliance-certificate.html',
  styleUrls: ['./compliance-certificate.scss'],
})
export class ComplianceCertificateComponent {
  private readonly router = inject(Router);
  private readonly authService = inject(AuthService);
  private readonly reports = inject(ReportsService);

  readonly createdBy = this.generatedBy();
  readonly certificate = signal<ComplianceCertificate | null>(null);
  readonly loading = signal(false);
  readonly error = signal<string | null>(null);
  private ownerId: string | null = null;

  onOwnerChange(owner: ReportOwnerOption): void {
    this.ownerId = owner.userId;
    this.loading.set(true);
    this.error.set(null);
    this.certificate.set(null);
    this.reports.getComplianceCertificate(owner.userId)
      .pipe(finalize(() => this.loading.set(false)))
      .subscribe({
        next: certificate => this.certificate.set(certificate),
        error: err => this.error.set(err?.error?.error ?? 'Could not load this owner’s compliance record.'),
      });
  }

  private generatedBy(): string {
    const user = this.authService.currentUser();
    if (!user) return 'Unknown user';
    const name = `${user.firstName ?? ''} ${user.lastName ?? ''}`.trim();
    return name || user.email || 'Unknown user';
  }

  goBack(): void {
    this.router.navigate(['/reports/compliance'], { queryParams: this.ownerId ? { owner: this.ownerId } : {} });
  }

  print(): void {
    window.print();
  }

  private formatDate(value: string | null, withTime = false): string {
    if (!value) return '—';
    return new Date(value).toLocaleString('en-ZA', withTime
      ? { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' }
      : { day: 'numeric', month: 'long', year: 'numeric' });
  }

  dateGenerated(c: ComplianceCertificate): string { return this.formatDate(c.dateGenerated, true); }
  lastChecked(c: ComplianceCertificate): string { return this.formatDate(c.lastChecked, true); }
  validUntil(c: ComplianceCertificate): string { return this.formatDate(c.validUntil); }
  expiry(value: string): string { return this.formatDate(value); }

  async downloadPdf(): Promise<void> {
    const c = this.certificate();
    if (!c) return;

    const { default: jsPDF } = await import('jspdf');
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    pdf.setTextColor(c.isCompliant ? 15 : 185, c.isCompliant ? 118 : 28, c.isCompliant ? 110 : 28);
    pdf.setFontSize(18);
    pdf.text(c.isCompliant ? 'DocuVault Certificate of FICA Compliance' : 'DocuVault Compliance Status Statement', 20, 28);
    pdf.setTextColor(23, 33, 43);
    pdf.setFontSize(11);

    const rows: [string, string][] = [
      ['Reference', c.certificateId],
      ['Date generated', this.dateGenerated(c)],
      ['Generated by', this.createdBy],
      ['Document owner', c.ownerName],
      ['Entity type', c.entityType],
      ['Identification', c.identification],
      ['Compliance status', c.overallStatus],
      ['Compliance', `${c.compliancePercentage}%`],
      ['Risk level', c.riskLevel],
      ['Last compliance check', this.lastChecked(c)],
      ['Valid until', c.isCompliant ? this.validUntil(c) : 'Not applicable (not compliant)'],
      ['Verification hash', c.verificationHash],
    ];
    let y = 44;
    for (const [label, value] of rows) {
      pdf.setFont('helvetica', 'bold');
      pdf.text(label, 20, y);
      pdf.setFont('helvetica', 'normal');
      pdf.text(value, 78, y);
      y += 9;
    }

    if (c.issues.length) {
      y += 4;
      pdf.setFont('helvetica', 'bold');
      pdf.text('Outstanding', 20, y);
      pdf.setFont('helvetica', 'normal');
      for (const issue of c.issues) {
        y += 7;
        pdf.text(`• ${issue}`, 24, y, { maxWidth: 165 });
      }
    }

    pdf.save(`${c.certificateId}.pdf`);
  }
}
